version: '3.8'

services:
  alina-orchestrator:
    image: python:3.11-slim
    container_name: alina-orchestrator
    volumes:
      - ./:/app
      - alina-data:/data
    working_dir: /app
    command: ["python", "-m", "agent_alina.core"]
    environment:
      - PYTHONUNBUFFERED=1
      - ALINA_CONFIG=/app/config.yaml
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 12G
    depends_on:
      - postgres
      - redis
    networks:
      - alina-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 24G
    networks:
      - alina-net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=alina
      - POSTGRES_PASSWORD=alina_pass
      - POSTGRES_DB=alina_memory
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
    networks:
      - alina-net

  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - alina-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - alina-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - prometheus
    networks:
      - alina-net

volumes:
  alina-data:
  ollama-data:
  postgres-data:
  redis-data:
  prometheus-data:
  grafana-data:

networks:
  alina-net:
    driver: bridge
    internal: true
